language: node_js
node_js:
  - "node"

cache: npm

script: npm run start

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: /
  on:
    branch: api
