language: node_js
node_js:
  - "node"

cache: npm

script: npm run build

deploy:
  provider: pages:git
  skip_cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  edge: true
  on:
    branch: gh-pages
